apiVersion: apps/v0.0.1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: eu.gcr.io/iscte-es2/springio/iscte-es2-restful:v0.0.1
        ports:
        - containerPort: 8080
